### ISSUE TITLE
Additional packages for full Quick Sync capabilities in official docker images

### ISSUE THREAD

**Issue by Shadowghost** [jellyfin/jellyfin-build#12]
It has been discussed in multiple issues that our official Docker images do not fully support Intel Quick Sync on recent chipsets because non-free drivers are required. We were concerned about their licensing and therefore refrained from including those packages.

Since nobody on the team nor anyone in the issues was willing to take the time to check all licenses we persisted in not redistributing them.

I took the time to actually check all licenses of the packages and their source repos and check if they allow redistribution:

| Required | Package | License(s) | Redistributable |
| ------------- | ------------- | ------------- | ------------- |
| yes <br/> (driver selfbuilding and ffmpeg) | `libva` <br/> `libva-dev` | Package: [Expat, Other and GPL2+](https://metadata.ftp-master.debian.org/changelogs//main/libv/libva/libva_2.10.0-1_copyright) <br/> Source: [Expat](https://github.com/intel/libva/blob/master/COPYING) | yes |
| yes | `intel-media-driver-non-free` | Package: [Expat and BSD-3-clause](https://metadata.ftp-master.debian.org/changelogs//non-free/i/intel-media-driver-non-free/intel-media-driver-non-free_21.1.1+ds1-1_copyright) <br/> Source: [MIT and BSD-3-clause](https://github.com/intel/media-driver#readme) | yes |
| yes | `intel-opencl-icd` | Package: [MIT, BSD-3-clause and SGI](https://metadata.ftp-master.debian.org/changelogs//main/i/intel-compute-runtime/intel-compute-runtime_20.44.18297-1_copyright) <br/> Source: [MIT](https://github.com/intel/compute-runtime/blob/master/LICENSE.md) | yes |
| no | `intel-gpu-tools` | Package: [MIT](https://metadata.ftp-master.debian.org/changelogs//main/i/intel-gpu-tools/intel-gpu-tools_1.25-2.1_copyright)  | yes |

All used licenses explicitly allow redistribution in binary form if the license is provided (which Debian does in their packages).

There shouldn't be any problems for us including those packages in our images.

----
Edit:
`intel-opencl-icd` should not be used until [this commit](https://github.com/intel/compute-runtime/commit/17051459eacc2979e039ca6669b4c247b6d75fb1) is included in the Debian package. Until then we need to explicitly install the official `.deb`s from [intel/compute-runtime](https://github.com/intel/compute-runtime/releases/latest)

Comment by @nyanmisaka: If we decide to include the non-free driver, we should uncomment [these lines](https://github.com/jellyfin/jellyfin-ffmpeg/blob/883570db52d230f7f9ab6c532069002d7a5ed90c/docker-build.sh#L161-L181) in the jellyfin-ffmpeg build script and add the license to [debian/copyright](https://github.com/jellyfin/jellyfin-ffmpeg/blob/jellyfin/debian/copyright). Using old drivers from debian/ubuntu repo will miss many fixes and improvements for newer chips.

----
Ideally this changes are required:
* [uncomment the ffmpeg lines](https://github.com/jellyfin/jellyfin-ffmpeg/blob/883570db52d230f7f9ab6c532069002d7a5ed90c/docker-build.sh#L161-L181) to automatically build and ship the nonfree driver with our ffmpeg package
* use the latest `.deb`s from [intel/compute-runtime](https://github.com/intel/compute-runtime/releases/latest) instead of old distro packages

----
Updated Dockerfile for Jellyfin: [gist](https://gist.github.com/Shadowghost/2ed30d6d64418e899e0a7c065bcaa585)
Bash script to manually build and install the nonfree driver: [gist](https://gist.github.com/Shadowghost/feffcb8f323570c43c592acd75795a46)

----

If I missed any required packages feel free to comment and I'll check them too.

**Comment by Shadowghost** [comment]
Since I didn't understand that our ffmpeg can ship the driver too, I initially built a Docker base image which includes all necessary steps do build the driver. Ontop of that Jellyfin can then be installed in a seperate build step, not requiring the driver to be rebuilt on every CI run:

System base image: [gist](https://gist.github.com/Shadowghost/4df3e6e370f5a6cad3580c291bdd8fb7)
Jellyfin unstable image: [gist](https://gist.github.com/Shadowghost/bd69ec857ea3d7ac4df1241d190ab814)

**Comment by Shadowghost** [comment]
If https://github.com/jellyfin/jellyfin-ffmpeg/pull/89 is merged the next version of jellyfin-ffmpeg ships the source-built driver, so no further changes to our current docker images are required.

**Comment by nyanmisaka** [comment]
I think this can be closed?
