### ISSUE TITLE
Debian packages should reload systemd in postinst

### ISSUE THREAD

**Issue by TwizzyDizzy** [jellyfin/jellyfin-build#2]
Hi folks,

when you upgrade jellyfin and do not reboot before doing any action (stop, start, reload) on the jellyfin systemd unit, systemd will complain that the unit file (or one of the unit's drop-ins) has been changed and systemd should be reloaded

A `/bin/systemctl --system daemon-reload` in the postinst of the control part of the package should fix this.

Sorry, if this is not the correct repository - just point me to the correct one instead :)

Cheers & thanks
Thomas

**Comment by dkanada** [comment]
I think that behavior is standard for systemd services, so I'm not sure we actually need to change anything here. @joshuaboniface can comment on best practices though.

**Comment by joshuaboniface** [comment]
As far as I know this shouldn't be required, at least not in the packages I've seen. I've never seen or heard it be an issue.

**Comment by dkanada** [comment]
I have to reload the unit files relatively often after updates, maybe I'm doing something wrong :laughing:

**Comment by TwizzyDizzy** [comment]
Curious. Well then I'll try to get a bit more detailed errors messages and debugging information (e.g. hash-summing  the unit files before and after an upgrade) and get back to you after the next upgrade.

To be frank: I'm not that much into packaging guidelines for Debian, so I will just wait for the next time that the message appears and will get back to you, OK? Actually I had a look at the **mariadb-server** packages before (to have a reference) and they are doing it. But yeah, like I said: gonna get back to you with more detailed information.

EDIT: it may also be relevant, that I am not upgrading from the repositories but from the `.deb` release assets via `dpkg -i`. I know that this is not good practice and I should use your repo in order to verify the authenticity against your keys.

Cheers
Thomas

**Comment by TwizzyDizzy** [comment]
Turns out, this has nothing to do with an upgrade. Happens without one, as you can see here:

```
root@pi:~# systemctl status jellyfin
Warning: The unit file, source configuration file or drop-ins of jellyfin.service changed on disk. Run 'systemctl daemon-reload' to reload units.
● jellyfin.service - Jellyfin Media Server
   Loaded: loaded (/lib/systemd/system/jellyfin.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/jellyfin.service.d
           └─jellyfin.service.conf
   Active: active (running) since Fri 2019-12-13 22:39:31 CET; 1 day 18h ago
 Main PID: 774 (jellyfin)
    Tasks: 27 (limit: 4915)
   Memory: 312.7M
   CGroup: /system.slice/jellyfin.service
           └─774 /usr/bin/jellyfin --restartpath=/usr/lib/jellyfin/restart.sh --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg

Dec 15 09:21:10 pi jellyfin[774]: [09:21:10] [INF] Watching directory /media/external/sync/MUSIC/Promo
Dec 15 09:21:10 pi jellyfin[774]: [09:21:10] [INF] Watching directory /media/external/sync/MUSIC/Vinyl
Dec 15 09:21:10 pi jellyfin[774]: [09:21:10] [INF] Watching directory /media/external/sync/MUSIC/Tracks
Dec 15 09:21:10 pi jellyfin[774]: [09:21:10] [INF] Watching directory /media/external/sync/MUSIC/HQ-Downloads
Dec 15 09:21:10 pi jellyfin[774]: [09:21:10] [INF] Watching directory /media/external/sync/MUSIC/HQ-CDs
Dec 15 15:05:50 pi jellyfin[774]: [15:05:50] [INF] IntervalTrigger fired for task: Check for plugin updates
Dec 15 15:05:50 pi jellyfin[774]: [15:05:50] [INF] Queueing task PluginUpdateTask
Dec 15 15:05:50 pi jellyfin[774]: [15:05:50] [INF] Executing Check for plugin updates
Dec 15 15:05:50 pi jellyfin[774]: [15:05:50] [INF] Check for plugin updates Completed after 0 minute(s) and 0 seconds
Dec 15 15:05:50 pi jellyfin[774]: [15:05:50] [INF] ExecuteQueuedTasks
```

Still have to nail it down though.

Cheers
Thomas
