### ISSUE TITLE
Update builds for Android TV app

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-build#3]
A while ago the `build` file was [renamed](https://github.com/jellyfin/jellyfin-androidtv/commit/9bfb1c7a8e8ba1e1bfd8a353ebe288fc2bff5ef1) to `build.sh` in the Android TV repository.

A bit later the Amazon and Google specific flavors were [removed](https://github.com/jellyfin/jellyfin-androidtv/commit/1ca6abdd1388489d920243d0ea2e9732d8343c23#diff-39e7d8c00954e920b98e7636f0ac30b2) and we only have a single universal flavor now.

The first change needs changes in the build repository, I'm not really sure about the second one.

**Comment by thornbill** [comment]
We also need to use the `release` branch instead of `master` so that we can use a fixed version of the apiclient library.
